apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name  }}-immich-library-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.quote  }}
